product/Controllers/MVCPrjsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProductDataAccessLib;
namespace product.Controllers
{
    public class MVCPrjsController : Controller
    {
        // GET: MVCPrjs

        [HttpGet]
        public ActionResult Addproduct()
        {
            productDAL dal = new productDAL();
            var cid=dal.getcategoryid().ToList();
            ViewData.Add("cid", cid);
            return View();
        }

        [HttpPost]
        public ActionResult Addproduct(tbl_product p)
        {
            productDAL dal = new productDAL();
            var cid = dal.getcategoryid().ToList();
            ViewData.Add("cid", cid);
            if (ModelState.IsValid)
            {

                
                dal.addproduct(p);

                var message = "Record added successfully!";


                ViewData.Add("message", message);
            }
            
          return View();
        }
        public ActionResult viewproduct()
        {
            productDAL dal = new productDAL();
             var d=dal.Viewproduct();
            return View(d);
        }
        public ActionResult Showcategoryname(string id)
        {
            productDAL dal = new productDAL();
           var d = dal.getcategorynames(id);
            return View(d);

        }
    }
}

product/Views/MVCPrjs/Addproduct.cshtml
@model ProductDataAccessLib.tbl_product

@{
    ViewBag.Title = "Addproduct";
    var cid = new SelectList((List<string>)ViewData["cid"]);
    
}

@using (Html.BeginForm())
{
    <h3>Welcome!Add Product here </h3>
    <table class="table table-bordered">
        <tr>
            <th> @Html.Label("select category"):</th>
            <td>
                @Html.DropDownListFor(model => model.categoryid, cid)
            </td>
        </tr>

        <tr>
           
            <th>@Html.LabelFor(model => model.productname):</th>
            <td>
                @Html.TextBoxFor(model => model.productname)
                @Html.ValidationMessageFor(model => model.productname, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <th>@Html.LabelFor(model => model.description):</th>
            <td>
                @Html.TextBoxFor(model => model.description)
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <th> @Html.LabelFor(model => model.price):</th>
            <td>
                @Html.TextBoxFor(model => model.price)
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <th>
                <input type="submit" value="add product" />
            </th>
            <td>
                @if (ViewData["message"] != null)
                {
                <span>
                    @ViewData["message"]
                </span>
                }
            </td>
        </tr>



    </table>
    <p>
        @Html.ActionLink("view product", "viewproduct")
    </p>
   
}

product/Views/MVCPrjs/Showcategoryname.cshtml
@model ProductDataAccessLib.tbl_category

@{
    ViewBag.Title = "Showcategoryname";
}

<h2>Category Details</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.categoryid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoryname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryname)
        </dd>

    </dl>
</div>

product/Views/MVCPrjs/viewproduct.cshtml
@model IEnumerable<ProductDataAccessLib.tbl_product>

@{
    ViewBag.Title = "viewproduct";
}

<h3>Your Product Details are here!</h3>


<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.productid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.categoryid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.productname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.Label("category name")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.productid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.categoryid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.productname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
       <td>
           <button type="button"  onclick="location.href='@Url.Action("Showcategoryname","MVCPrjs",new {@id=item.categoryid })'">show category</button>
       </td>
    </tr>
}

</table>

product/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>